[directory]
truncation_length = 5
truncate_to_repo = false

[username]
disabled = true

[jobs]
symbol = "+ "
threshold = 4

[memory_usage]
show_percentage = true
show_swap = true
threshold = -1
style = "bold dimmed green"
disabled = false
